variables:
  GIT_DEPTH: 1                               # Create a shallow copy
  BOT_NAME: "GitLab Runner Bot"              # Bot's name that appears in the commit log
  BOT_EMAIL: "au685727@uni.au.dk"            # Bot's email, not important
  GITLAB_USER: "au656408"                    # Replace with your GitLab username
  GITLAB_TOKEN: "glpat-Sy9678A5EgwRAN5djdZa" # Replace with your personal access token

stages:
  - tag
  - build

tag:
  image: alpine:latest
  stage: tag
  before_script:
    - apk add --no-cache git
    - git config --global user.email "$BOT_EMAIL"
    - git config --global user.name "$BOT_NAME"
  script:
    - git tag -f latest  # Create or update the tag named 'latest'
    - git push -f https://$GITLAB_USER:$GITLAB_TOKEN@gitlab.au.dk/wao-exercises1/eatfresh/eatfresh.tablebookingservice.git latest
  only:
    - main

build:
  image: griefed/docker-with-buildx:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use
  script:
    - docker pull "$CI_REGISTRY_IMAGE:latest" || true
    - docker buildx build --push --tag "$CI_REGISTRY_IMAGE:latest" --platform linux/arm64/v8,linux/amd64 --tag "$CI_REGISTRY_IMAGE:latest" .
  only:
    - tags
    - main
