stages:
  - build

build:
  image: griefed/docker-with-buildx:latest
  stage: build

  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use
  script:
    - docker pull "$CI_REGISTRY_IMAGE:latest" || true
    - export IMAGE_TAG="$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA"
    - docker buildx build --push --tag "$CI_REGISTRY_IMAGE:latest" --platform linux/arm64/v8,linux/amd64 --tag "$CI_REGISTRY_IMAGE:${CI_COMMIT_TAG-latest}" --tag "$CI_REGISTRY_IMAGE:$IMAGE_TAG" .
  only:
    - main
    - tags
