version: '3.8'

networks:
  EatFresh_network:
    driver: bridge

services:
  mongo-express:
    image: mongo-express
    depends_on: 
      - mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - EatFresh_network

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - EatFresh_network
  
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USERNAME: guest
      RABBITMQ_DEFAULT_PASSWORD: guest
    networks:
      - EatFresh_network

  tablebookingapp:
    depends_on:
        - mongo
        - rabbitmq
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4000:4000"
    environment:
      PORT_ARG: 4000
    networks:
      - EatFresh_network


